FROM python:3.8

# Atualizar o pip para a versão mais recente
RUN python -m pip install --upgrade pip

# Copie o código do Fornecedor para o container
COPY fornecedor.py /app/fornecedor.py

# Defina o diretório de trabalho
WORKDIR /app

# Instale as bibliotecas necessárias (no caso, paho-mqtt)
RUN pip install paho-mqtt

# Comando para executar o script do Fornecedor
CMD ["python", "fornecedor.py"]
